### ISSUE TITLE
Sometime channel.connect hang

### ISSUE THREAD

**Issue by hanh45** [lucastheisen/jsch-extension#6]
Hi,
I using jsch-extension in project of monitor thousands Linux server.
Sometime, any server hang infinity with exception:

> [Connect thread xx.xx.xx.xx session] INFO  com.pastdev.jsch.Slf4jBridge - Caught an exception, leaving main loop due to Read timed out

I edited close function in CommandRunner class and fixed this issue.

Add new code:

```
     if(channel.isClosed()){
          exitCode = channel.getExitStatus();
          break;
     }
```

Please verify and update source code:

``` java
     public int close() {
            int exitCode = -2;
            if ( channel != null ) {
                try {                  
                    IOUtils.closeAndLogException( stdIn );
                    IOUtils.closeAndLogException( stdOut );
                    IOUtils.closeAndLogException( stdErr );
                    int i = 0;
                    while ( (exitCode = channel.getExitStatus()) == -1 ) {
                        logger.info( "waiting for exit {}", i++ );

                        if(channel.isClosed()){
                            exitCode = channel.getExitStatus();
                                break;
                        }

                        try {
                            Thread.sleep( 100 );
                        }
                        catch ( InterruptedException e ) {}
                    }
                }
                finally {
                    if ( channel.isConnected() ) {
                        channel.disconnect();
                    }
                }
            }
            logger.trace( "`{}` exit {}", command, exitCode );
            return exitCode;
        }
```

P/S:
I deleted 3 private property because them not use.

```
private OutputStream passedInStdErr;
private InputStream passedInStdIn;
private OutputStream passedInStdOut;
```

Thanks

**Comment by lucastheisen** [comment]
Thanks for your report...  I will have to look a bit deeper into this when I get a free moment.  Are you using the `open` or `execute` method?  Also, do you have a unit test that could demonstrate this issue?

**Comment by hanh45** [comment]
Hi @lucastheisen ,
I use ```execute``` function.

My program run hundreds threads concurrent, once thread have a CommandRunner  object with other user, password or ip.

I have set timeout for test but sometime have any threads hang:
```
SessionManager (line 59) session.connect(30000); 
CommandRunner (line 206) channel.connect(30000);
```
In log file when thread hang, only a line and nothing:
```[Connect thread xx.xx.xx.xx session] INFO com.pastdev.jsch.Slf4jBridge - Caught an exception, leaving main loop due to Read timed out```

I research CommandRunner.java code and see the close function can infinity with code block (line 230 -> 236):
```
while ( (exitCode = channel.getExitStatus()) == -1 ) {
                        logger.trace( "waiting for exit {}", i++ );
                        try {
                            Thread.sleep( 100 );
                        }
                        catch ( InterruptedException e ) {}
                    }
```
In http://epaul.github.io/jsch-documentation/javadoc/com/jcraft/jsch/Channel.html#getExitStatus()
```
Returns:
the exitstatus returned by the remote command, or -1, if the command not yet terminated (or this channel type has no command).
```
```channel.getExitStatus()```:  Not always returns -1
I think channel can closed by jsch (channel can # null) and ```channel.getExitStatus()``` return # -1 => hang infinity.

I only check if channel was closed and current, my program have not thread hang.

**Comment by lucastheisen** [comment]
@hanh45, sorry for the delay, I cleaned up your solution a little, went with:

```
                    while ( !channel.isClosed() ) {
                        logger.trace( "waiting for exit {}", i++ );
                        try {
                            Thread.sleep( 100 );
                        }
                        catch ( InterruptedException e ) {}
                    }
                    exitCode = channel.getExitStatus();
```

Release version 1.8 should show up on maven central by tomorrow.
