### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by hookumsnivy** [lucastheisen/jsch-extension#7]
This is a question and not really an issue:

Does this library support multi-threading? If so, is there a special way to configure the library to do so?
I'm running into an issue where 2 threads are trying to write a file (different files) at roughly the same time. I haven't traced through all the code (yet) to figure out if they are both going to use the same connection, but my guess is that they will.
It's possible that I'm not using the library in the expected way to support multiple threads.
I'm using Spring and I configure a Path that I will essentially be using as the root path under which all my files appear. From then on, I create directories and files using said path. 

Example:
```
@Bean
    public Path storagePath(String storageRootPath, String storageSubPath,
                            String userName, String password) throws JSchException,
            URISyntaxException, IOException {
        FileSystem fs;
        URI uri = new URI(storageRootPath);
            DefaultSessionFactory sessionFactory = new DefaultSessionFactory(userName, null, null);
            sessionFactory.setKnownHosts(this.getClass().getResourceAsStream("/known_hosts"));
            sessionFactory.setPassword(password);
            Map<String, Object> environment = Maps.newHashMap();
            environment.put("defaultSessionFactory", sessionFactory);
            environment.put("watchservice.inotify", true);

            fs = FileSystems.newFileSystem(
                    uri,
                    environment,
                    this.getClass().getClassLoader()
            );
        return fs.getPath(storageSubPath).toAbsolutePath();
    }
```
Elsewhere in the code, there's something like this where rootPath is the value from the preconfigured bean:
```
            Path filePath = rootPath.resolve(subPath);
            Path parentPath = filePath.getParent();
            if (Files.notExists(parentPath)) {
                Files.createDirectories(parentPath);
            }
            Files.copy(content, filePath, StandardCopyOption.REPLACE_EXISTING);
```

**Comment by lucastheisen** [comment]
@hookumsnivy , this library, as well as `jsch-nio` (which you appear to be using in this example) are written on top of Jsch which is _not_ threadsafe.  I think the simplest approach for you might be to create one `FileSystem` per thread.  You could do this by creating a thread pool which initializes each thread with its own `FileSystem` instance and caches the insance in a `ThreadLocal<FileSystem>`.  This should make the thread safety _fairly_ transparent.

**Comment by hookumsnivy** [comment]
@lucastheisen Sorry I put this question in the wrong place, I was looking at the related libraries at the time.
Unfortunately creating 1 FileSystem per thread won't work because the provider won't let you create multiple file systems with the same base url. Fortunately for my use case, I can just use synchronized blocks. It's not ideal, but it will have to do.
